### ISSUE TITLE
[MCOMPILER-277] Compilation error while compiling for 1.6 using JDK 1.8

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#485]
**[Yoram Michaeli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yorammi)** opened **[MCOMPILER-277](https://issues.apache.org/jira/browse/MCOMPILER-277?redirect=false)** and commented

I have JDK 8 (Java version: 1.8.0_91, vendor: Oracle Corporation) installed with Maven 3.2.5 and the maven-compiler-plugin is set for source and target version 1.6.
I'm getting the following compilation error:xxx is not abstract and does not override abstract method getParentLogger() in javax.sql.CommonDataSource
Switching the environment (PATH and JAVA_HOME) to work with JDK 6 (Java version: 1.6.0_45, vendor: Sun Microsystems Inc.) compiles OK.
Seems to me that the plugin is not really compiles for 1.6.

---

**Affects:** 3.3, 3.5.1

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

It compiles with JDK 8 for source/target which is something different than really using JDK 6. In JDK 8 have several changes in particular in javax. etc. see http://docs.oracle.com/javase/7/docs/api/javax/sql/CommonDataSource.html#getParentLogger() If you need to compile really for JDK 6 you should use JDK 6 (may be you need to use toolchain to correctly handle that).

**Comment by jira-importer** [comment]
**[Yoram Michaeli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yorammi)** commented

So what is the point for using that feature of the plugin?
If I have a server that needs to support more than one project which each project need to be compiled to a different JDK and installing more than one JDK is not an option?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

This is not a feature of the plugin it's a feature of the underlying JDK (or to be more accurate of the javac) which support target/source option with all the drawbacks it has...If you need to support different JDK's there is not really an other way to support that via installing the needed JDK's. Using toolchains is the correct way to handle this in Maven.

If you have a server that needs to support different JDK's the best way is to install the needed JDK's...and configure Toolchains correctly than maven-compiler-plugin will use the appropriate JDK (javac) and it will work...

**Comment by jira-importer** [comment]
**[Yoram Michaeli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yorammi)** commented

Well, my case is actually different. I need to support compiling the same code for JDK 1.6 and JDK 1.7 for 2 production systems that need to run side-by-side for a while so I've used 2 maven profiles, one compiles for JDK 1.6 and one for 1.7.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

I don't see any differences. You need to support two different JDK's which is nothing unusual. So you have to have installed the two JDK's and compile the whole project with JDK 1.6 or with JDK 1.7 that's it...This makes it absolutely sure that there are no compatibility issues using different JDK's means for example using JDK 1.7 in relationship with source/target for JDK 6....( I have done that several times with IBM Java 1.6 / IBM Java 1.7 / Oracle JDK 1.6 / Oracle JDK 1.7 etc. ).
The simplest solution for such things is to [configure Maven Toolchain](https://github.com/khmarbaise/maven-toolchain-example) and use it via that...

Furthermore you can check the language level you are using by http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/ to be sure you don't use JDK 1.7 features while you are compiling for JDK 1.6 ...etc.

**Comment by jira-importer** [comment]
**[Yoram Michaeli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yorammi)** commented

Thanks Karl. I'll go for the Toolchain solution
