### ISSUE TITLE
[MCOMPILER-179] Warnings 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#844]
**[Sascha Vogt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=saschavogt)** opened **[MCOMPILER-179](https://issues.apache.org/jira/browse/MCOMPILER-179?redirect=false)** and commented

If one error occurs, all warnings are shown as error as well. Up to `2.3.2` this was not the case. Sample output `2.4` and higher:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] bad path element "": no such file or directory
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[19,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[20,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[24,15]
[unchecked] unchecked conversion
found   : java.util.List
required: java.util.List<java.lang.String>
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[29,29]
getList() in de.maybebuggy.sample.Main cannot be applied to (int)
[INFO] 4 errors
```

Sample output `2.3.2`:

```
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[19,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[20,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[24,15]
[unchecked] unchecked conversion
found   : java.util.List
required: java.util.List<java.lang.String>
[INFO] 3 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[29,29]
getList() in de.maybebuggy.sample.Main cannot be applied to (int)
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

With the current behavior it is extremely hard to spot the error if there are multiple warnings in a project.

---

**Affects:** 2.4, 2.5, 2.5.1

**Issue Links:**
- [MCOMPILER-120](https://issues.apache.org/jira/browse/MCOMPILER-120) Javac compiler plugin doesn't support -Werror

4 votes, 9 watchers

**Comment by jira-importer** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

I have now verified that IT for MCOMPILER-120 works with p-c 1.9.3-SNAPSHOT. But it's not really a pretty solution for MCOMPILER-120 as the plugin's error message will say that it couldn't parse the compiler output.

I think that the main problem is that the compilation result (ok/nok) is based on if there's an error message returned. A better solution would be to have a separate result value, and then have debug/warning/error messages for logging only.

**Comment by jira-importer** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

IT added in http://svn.apache.org/r1407250

**Comment by jira-importer** [comment]
**[Eric Sirianni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sirianni)** commented

I am still seeing this issue in maven 3.1.1.  See this [Hadoop JIRA](https://issues.apache.org/jira/browse/HDFS-5462) as an example.
