### ISSUE TITLE
[MCOMPILER-271] APT generated classes not visible during test compilation

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#351]
**[Oliver Drotbohm](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oliver.gierke)** opened **[MCOMPILER-271](https://issues.apache.org/jira/browse/MCOMPILER-271?redirect=false)** and commented

After upgrading the Maven Compiler Plugin to 3.5.1, I see compilation errors with builds that work on 3.5. The symptom is that classes generated by an APT plugin are not visible on the test class path when `target/generated-sources/annotations` is used as output folder.

I'll attach a sample project that shows the failure if you run `mvn clean test-compile`.

Two things make the project work:

1. Downgrade to 3.5 (which makes me think any of the fixes made for MCOMPILER-240 has to do with this).
2. Change `annotations` segment  of the output path to something other than `annotations`.

Especially the latter puzzles me as it seems like this path is explicitly not added to the test compile classpath.

---

**Affects:** 3.5.1, 3.6.1

**Attachments:**
- [compiler-plugin-bug.zip](https://issues.apache.org/jira/secure/attachment/12816300/compiler-plugin-bug.zip) (_5.98 kB_)

0 votes, 9 watchers

**Comment by jira-importer** [comment]
**[Phillip Webb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pwebb)** commented

This issue is unfortunately quite important for Spring Boot users and as a result we're going use Maven Compiler 3.5.0 in the Spring Boot 1.4 parent POM. I'd love to be able to upgrade to 3.5.2 when it's available so please let us know if there's anything we can do to help fix this issue.

**Comment by jira-importer** [comment]
**[Oliver Drotbohm](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oliver.gierke)** commented

Did you mean 3.5.0?

**Comment by jira-importer** [comment]
**[Phillip Webb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pwebb)** commented

Yes, edited the comment.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

BTW: The previous version of [maven-compiler-plugin](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.maven.plugins%22%20AND%20a%3A%22maven-compiler-plugin%22) is `3.5` and not `3.5.0`

**Comment by jira-importer** [comment]
**[Andreas Gudian](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agudian)** commented

Sorry for the long silence, I'll look into it in the next couple of days or so.

**Comment by jira-importer** [comment]
**[Andreas Gudian](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agudian)** commented

I just played around a bit.  and changing the build-section of the pom in the example to this helps (removing the apt-maven-plugin):

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.5.1</version>
            <configuration>
                <source>${java.version}</source>
                <target>${java.version}</target>
                <compilerArgument>-parameters</compilerArgument>
                <annotationProcessorPaths>
                    <dependency>
                        <groupId>com.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydsl.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.hibernate.javax.persistence</groupId>
                        <artifactId>hibernate-jpa-2.1-api</artifactId>
                        <version>1.0.0.Final</version>
                    </dependency>
                </annotationProcessorPaths>
                <annotationProcessors>
                    <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                </annotationProcessors>
            </configuration>
        </plugin>
    </plugins>
</build>
```

I'm pretty sure this has nothing to do with the incremental compilation stuff.

It is defintely a side-effect of the changes I made for MCOMPILER-240. What happens is that if the path configured with `generatedSourcesDirectory` ( (which defaults to `target/generated-sources/annotations`) or the equivalent for `test-compile` is part of the project's compile-source-roots, then that directory will be ignored for compilation, as the annotation processing done by the compilation step itself already takes care of compiling the sources it generates (regardless of whether `annotationProcessorPaths` is used or not). So the assumption is that the path configured with `generatedSourcesDirectory` would only contain sources that are already compiled.

So it doesn't seem like something we can nicely fix in the compiler-plugin. I don't think we should try to determine if any files within the generated-sources directory were generated by the compiler-plugins compilation call and thus are already compiled, or if they have been placed at that location by another plugin execution.

And as pointed out, the other alternative to use only the compiler-plugin or to change the output path for the apt-plugin to a directory that doesn't overlap with the (configured or defaulted) `generatedSourcesDirectory` of the compiler-plugin. I always do that with the compiler-plugin only, as there's usually no need to split APT source generation from compilation.

I suggest closing this as Wont-Fix, with the explanation above. Is that okay with you, [Oliver Drotbohm](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oliver.gierke)?

**Comment by jira-importer** [comment]
**[Oliver Drotbohm](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oliver.gierke)** commented

I don't think it is. It's absolutely weird that all of a sudden there's now a magic path that is not included into compilation where it actually was before. Even more ironic, it's the default path that you'd use. As a user you don't get any kind of hint what could've gone wrong. Maven is blatantly claiming the types aren't available. Which leaves you with nothing but googling until you find this ticket.
